workflows:
  default-workflow:
    name: Build APK Métodos Numéricos
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Inicializar entorno Flutter y crear carpetas Android
        script: |
          # 1. Creamos la estructura base nativa primero
          flutter create . --overwrite --offline
          
          # 2. Obligamos a crear la carpeta lib si no existe
          mkdir -p lib
          
          # 3. Al puro final, movemos TU main.dart real para destruir la plantilla fea
          mv main.dart lib/main.dart
      - name: Conseguir dependencias de Flutter
        script: |
          flutter pub get
      - name: Construir el archivo APK de Android
        script: |
          flutter build apk --release
    publishing:
      github_releases:
        prerelease: false
        draft: false
